// Capacitor plugin settings - local paths for standalone build
include ':capacitor-android'
project(':capacitor-android').projectDir = new File('./capacitor-android')

include ':capacitor-mlkit-barcode-scanning'
project(':capacitor-mlkit-barcode-scanning').projectDir = new File('./capacitor-mlkit-barcode-scanning')

include ':capacitor-browser'
project(':capacitor-browser').projectDir = new File('./capacitor-browser')

include ':capacitor-camera'
project(':capacitor-camera').projectDir = new File('./capacitor-camera')

include ':capacitor-haptics'
project(':capacitor-haptics').projectDir = new File('./capacitor-haptics')

include ':capacitor-preferences'
project(':capacitor-preferences').projectDir = new File('./capacitor-preferences')

include ':capacitor-push-notifications'
project(':capacitor-push-notifications').projectDir = new File('./capacitor-push-notifications')

include ':capacitor-share'
project(':capacitor-share').projectDir = new File('./capacitor-share')

include ':capacitor-status-bar'
project(':capacitor-status-bar').projectDir = new File('./capacitor-status-bar')
