name: Build iOS App
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build:client
      - run: npx cap sync ios
      - run: cd ios/App && pod install --repo-update
      - run: cd ios/App && xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -derivedDataPath build -arch arm64 build
      - uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: ios/App/build/Release-iphoneos/
          retention-days: 30
